[package]
name = "preview"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus.workspace = true
dioxus-primitives.workspace = true

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]